### PR TITLE
Add oembed format

### PR DESCRIPTION
**Pull request by jsturek**
I've pushed this branch on to mediahub test site (https://mediahub-test.unl.edu) for you to test if working as desired.  I wasn't sure what you wanted so I took a shot in the dark.  Based format on https://oembed.com/.  For the video and rich (audio) I used our existing embed format for the `html` attribute value. 

~~Sample usage: https://mediahub-test.unl.edu/media/36?format=oembed~~
Updated Sample usage:
* https://mediahub-test.unl.edu/oembed?url=https%3A%2F%2Fmediahub-test.unl.edu%2Fmedia%2F36 (defaults to json output)
* https://mediahub-test.unl.edu/oembed?url=https%3A%2F%2Fmediahub-test.unl.edu%2Fmedia%2F36&format=json (specify json output)
* https://mediahub-test.unl.edu/oembed?url=https%3A%2F%2Fmediahub-test.unl.edu%2Fmedia%2F36&format=xml (specify xml output)

Invalid url or format will return 404

### CODE REVIEW

**Comment by ericras** [comment]
@macburgee1 - do you want to test this in Drupal with the sample URL above?

**Comment by macburgee1** [comment]
Thanks for working on this. It's a good start.

Would it be possible for us to support an API endpoint that accepts a query string? This is what most other oEmbed providers do. This is also the only way Drupal knows how to interact with an oEmbed provider.

**YouTube:**
```
URL scheme: https://*.youtube.com/watch*
URL scheme: https://*.youtube.com/v/*"
URL scheme: https://youtu.be/*
API endpoint: https://www.youtube.com/oembed
Example: https://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiwGFalTRHDA
Example: https://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiwGFalTRHDA&format=xml
Supports discovery via <link> tags
```

**Vimeo**
```
URL scheme: https://vimeo.com/*
URL scheme: https://vimeo.com/album/*/video/*
URL scheme: https://vimeo.com/channels/*/*
URL scheme: https://vimeo.com/groups/*/videos/*
URL scheme: https://vimeo.com/ondemand/*/*
URL scheme: https://player.vimeo.com/video/*
API endpoint: https://vimeo.com/api/oembed.{format}
Documentation: https://developer.vimeo.com/apis/oembed
Example: https://vimeo.com/api/oembed.xml?url=http%3A%2F%2Fvimeo.com%2F76979871
Example: https://vimeo.com/api/oembed.json?url=http%3A%2F%2Fvimeo.com%2F76979871
Supports discovery via <link> tags
```

UNL MediaHub (suggested):
```
URL scheme: http://mediahub-test.unl.edu/media/*
URL scheme: https://mediahub-test.unl.edu/media/*
API endpoint: https://mediahub-test.unl.edu/oembed
Example: https://mediahub-test.unl.edu/oembed?url=https%3A%2F%2Fmediahub-test.unl.edu%2Fmedia%2F36
```

We'd probably want to code it in such a way that it's domain agnostic when it comes to the domain used in the 'url' query string value. That way it doesn't matter if we're running in prod or test.

**Comment by macburgee1** [comment]
I neglected to address the format. While the wider campus community may find an XML return useful, we'll only need a JSON return for Project Herbie.

**Comment by macburgee1** [comment]
Good news - the resource is now loading on my end. The response JSON does't include a width or height, which are required by the spec and are causing rendering failure on my end. Can you include the width and height?

**Comment by macburgee1** [comment]
Thanks, Jeff! The video dimensions look good.

## Remove the `<div>` wrapper
When the `<iframe>` is rendered, it is wrapped in a `<div>`, which has 'wdn-responsive-embed' and 'wdn-aspect16x9' classes. I'm going to suggest that we remove that wrapper and leave it up to consumers to determine if they want to wrap the rendered oEmbed markup in a given usage.

## Add frameborder attribute to `<iframe>`
Let's add a `frameborder` attribute to the `<iframe>` element with a value of 0: `frameborder="0"`. By default, at least some browsers (including Chrome) will add a 4px gray border to an iframe. Other oEmbed providers, such as YouTube, add this attribute to standardize appearance across browsers.

## Thumbnail file extension
Currently, the thumbnail image URL is provided without a file extension: 'https://mediahub-test.unl.edu/media/36/image' for example. Drupal is expecting a file extension and fails to handle the image file correctly without its extension. In the example, the returned file is a JPEG. Is there a way we can return a URL that includes the file extension?

**Comment by macburgee1** [comment]
All looks good! Thanks!

**Comment by macburgee1** [comment]
I tested with audio and ran into a few minor issues:

## Set 'width' and 'height' in `<iframe>`
We're setting a height and a width on the JSON return but not in the `<iframe>` element. This causes problems on display:

image

The rendered media is fairly small (300px) and the control bar is cut off. Let's add height and width attributes to the `<iframe>` element.

It appears that with a width of 600px we need a height of 337px.

## Add frameborder attribute to `<iframe>`
Let's add `frameborder="0"` on this `<iframe>` element for the same reason as we do on video.

**Comment by macburgee1** [comment]
These changes test successfully for me.

**Pull request merged**
